
name: Build 7z.dll
on: [push, pull_request]

permissions:
  contents: read
  id-token: write
  attestations: write

jobs:

  build-7z-dll:
    runs-on: windows-2025-vs2026
    steps:
      - uses: actions/checkout@v6

      - name: Find vcvarsall path
        shell: cmd
        run: |
          for /f "usebackq tokens=*" %%i in (`vswhere -latest -property installationPath`) do (
            echo VCVARSALL_PATH=%%i\VC\Auxiliary\Build\vcvarsall.bat >> %GITHUB_ENV%
          )

      - name: Build 7z.dll (x64)
        shell: cmd
        run: |
          call "%VCVARSALL_PATH%" x64
          set SUBSYS=5.02
          set LFLAGS=/SUBSYSTEM:WINDOWS,5.02
          set ZIP7_DARKMODE=0
          cd CPP\7zip\Bundles\Format7zF
          nmake /NOLOGO
          if %errorlevel% neq 0 exit 1

      - name: Package 7z.dll
        shell: pwsh
        run: |
          Compress-Archive -Path CPP\7zip\Bundles\Format7zF\x64\7z.dll -DestinationPath 7z-dll-win-x64.zip

      - name: Generate SHA256 checksum
        shell: pwsh
        run: |
          $hash = (Get-FileHash -Algorithm SHA256 7z-dll-win-x64.zip).Hash.ToLower()
          "$hash  7z-dll-win-x64.zip" | Out-File -Encoding ascii 7z-dll-win-x64.zip.sha256
          Write-Output "SHA256: $hash"

      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@v2
        with:
          subject-path: 7z-dll-win-x64.zip

      - name: Upload 7z-dll-win-x64.zip
        uses: actions/upload-artifact@v6
        with:
          name: 7z-dll-win-x64
          path: |
            7z-dll-win-x64.zip
            7z-dll-win-x64.zip.sha256
